# Python

## Fundamentals

### Variables, data types (int, float, string, bool)

In [118]:
# Variable = a reuasable container for storing a value. 
#            a variable behvae as if it ware the value it contains 

In [119]:
age = 31

print(age)

31


In [120]:
print('You are ' + str(age) + ' year old')
print('You are', age, 'year old')
print(f'You are {age} years old')

You are 31 year old
You are 31 year old
You are 31 years old


In [121]:
# Basic Data Type 

# interger (number)

age = 31
players = 2
quantity = 5

print(f'You are {age} years old')
print(f'There are {players} players online')
print(f'You would like to buy {quantity} items')

You are 31 years old
There are 2 players online
You would like to buy 5 items


In [122]:
# Float (decimal)

gpa = 3.2
distance = 2.5
price = 10.25

print(f'You gpa is {gpa}')
print(f'You ran {distance}km')
print(f'The price is ₹{price}')

You gpa is 3.2
You ran 2.5km
The price is ₹10.25


In [123]:
# String (Text)

name = 'Naidu'
food = 'Tripel Rice'
email = "Naidu123@gmail.com"

print(f'Hello {name} you like {food} you email is {email}')

Hello Naidu you like Tripel Rice you email is Naidu123@gmail.com


In [124]:
# Boolean (only have 2 variable True or False)

online = True 
for_sale = False 
running = True

print(f'Are you online?: {online}')
print(f'Is the item for sale? {for_sale}')
print(f'Game Running {running}')



Are you online?: True
Is the item for sale? False
Game Running True


### Operators (arithmetic, comparison, logical)

In [125]:
# arithmetic Operators 

x = 2 
y = 5

print(x + y) # addition 
print(x - y) # subtraction 
print(x * y) # multiply 
print(x / y) # Divide return in decimal 
print(x // y) # Divide return in number or int 
print(x % y) # Divide and return reminder 

 


7
-3
10
0.4
0
2


In [126]:
# logical operators = used on conditional statements 

#                     and = checks two or more conditions if True
#                     or = checks if at least one conditions is Ture 
#                     not = True Become False, and reverse False become True 

# add 
temp = 25

if temp > 0 and temp < 30:  # if both condition is True 
    print('The temp is good')
else:
    print('The temp is bad') 



The temp is good


In [127]:
# or
temp = 15

if temp <= 0 or  temp >= 30:  # if one condition is True 
    print('The temp is bad')
else:
    print('The temp is good') 

The temp is good


In [128]:
# not

Sunny = False  # True become False , False become True

if not Sunny:
    print('It is cloudly outside')
else:
    print('It is sunny outside')

It is cloudly outside


In [129]:
# Comperision Operator 

print(10 == 10) # Equal to 

print(10 != 50) # Not Equal

print(10 < 50) # less then 

print(10 < 50) # greater then

print(10 <= 10) # less then equal to 

print(10 >= 50) # greater then equal to 

True
True
True
True
True
False


In [130]:
# Membership Operators 

 # in = find elemints in string , list etc 
 # not in = find elemints not in the string or list 

Rank = [1,2,3,4,5,6,7]

print(2 in Rank) 
print(2 not in Rank)

True
False


## Input/output operations

In [131]:
name = input('What is you name?: ')
age = int(input('How old are you? '))
height = float(input('How tall are you?: '))

age = age + 1

print('Hello ' + name)
print('you are ' + str(age) + ' Years old')
print('You are ' +  str(height) + 'cm tall')

Hello Naidu
you are 31 Years old
You are 155.5cm tall


### Comments and documentation

In [132]:
# Comments -> single line comment  

print('Hello world') # inline comment 

'''
Multiline 
comment '''

# Documentation

help(list)

Hello world
Help on class list in module builtins:

class list(object)
 |  list(iterable=(), /)
 |
 |  Built-in mutable sequence.
 |
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |
 |  Methods defined here:
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __contains__(self, key, /)
 |      Return bool(key in self).
 |
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __getitem__(self, index, /)
 |      Return self[index].
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for a

## Built-in Data Structures

### Lists (indexing, slicing, methods), Sets, Tuples

In [133]:
# Collection = Single "Variable" use to store multiple values 
#    List  = [] prdered and changeable. Duplicates OK
#    Set   = {} unordered and immutable, but Add/Remove OK. NO duplicates 
#    Tuple = () ordered and unchangeable. Duplicates Ok. FASTER

# List 

fruits = ['apple', 'ornage', 'banana', 'coconut']

print(fruits)

print(fruits[3])  # Indexing
fruits[0] = 'pineapple'
print(fruits)

print(fruits[0:3]) # slicing
print(fruits[::2]) # step of 2 





['apple', 'ornage', 'banana', 'coconut']
coconut
['pineapple', 'ornage', 'banana', 'coconut']
['pineapple', 'ornage', 'banana']
['pineapple', 'banana']


In [134]:
# Method 

fruits.append('mango') # add a element to list in last posision 
print(fruits)

fruits.remove('ornage') # remove element for the list 
print(fruits)

fruits.insert(2,'grapes')  # adding eliment in a 2 index 
print(fruits)

fruits.sort() # short the order 
print(fruits)

fruits.reverse() # reverse the order 
print(fruits)

print(fruits.index('coconut')) # return the index of the coconut position on list 

print(fruits.count('banana'))  # count how many banana in the fruits list 

fruits.clear()  # to Clear a list 
print(fruits)

['pineapple', 'ornage', 'banana', 'coconut', 'mango']
['pineapple', 'banana', 'coconut', 'mango']
['pineapple', 'banana', 'grapes', 'coconut', 'mango']
['banana', 'coconut', 'grapes', 'mango', 'pineapple']
['pineapple', 'mango', 'grapes', 'coconut', 'banana']
3
1
[]


In [135]:
# Set ->  {} unordered and immutable, but Add/Remove OK. NO duplicates 

fruits = {'apple', 'ornage', 'banana', 'coconut', 'coconut'}

print(fruits)

print(len(fruits)) # fint the len of any thing string,list,set etc

# method 
fruits.add('pineapple') # add element to set
print(fruits)

fruits.remove('banana') # remove element form set 
print(fruits)

fruits.pop() # remove random item form the list 

fruits.clear() # clear the set 


{'banana', 'ornage', 'apple', 'coconut'}
4
{'coconut', 'apple', 'banana', 'ornage', 'pineapple'}
{'coconut', 'apple', 'ornage', 'pineapple'}


In [136]:
# Tuple -> () ordered and unchangeable. Duplicates Ok. FASTER

fruits = ('apple', 'ornage', 'banana', 'coconut', 'coconut')

print(fruits)

# Method 

print(fruits.index('banana'))

fruits.count('coconut')

('apple', 'ornage', 'banana', 'coconut', 'coconut')
2


2

In [140]:
# Dictionary -> a collect of {key:value} 
#               ordered and changeable. No duplicates

capitals = { 'USA' : 'Washington D.C.',
             'India': 'New Delhi',
              'China': 'Beijing',
              'Russia': 'Moscow' }


# Methods 
print(capitals.get('India')) # provide key in get it will return values 

capitals.update({'Germany':'Berlin'}) # add new key,value pair in the list or change the old value 
capitals.update({'China': 'Singjan'})
print(capitals)


print(capitals.pop('China')) # remove chine key,value from the list 

print(capitals.popitem()) # remove last key,value form the list 

print(capitals.keys()) # return all the keys form dictionary

print(capitals.values()) # return all the values for dictionary

print(capitals.items()) # return all the key,value pairs in 2D list , tuple

capitals.clear() # this will clear the dictionary





New Delhi
{'USA': 'Washington D.C.', 'India': 'New Delhi', 'China': 'Singjan', 'Russia': 'Moscow', 'Germany': 'Berlin'}
Singjan
('Germany', 'Berlin')
dict_keys(['USA', 'India', 'Russia'])
dict_values(['Washington D.C.', 'New Delhi', 'Moscow'])
dict_items([('USA', 'Washington D.C.'), ('India', 'New Delhi'), ('Russia', 'Moscow')])


In [ ]:
# List Compreance 

nums = [1,2,3,4,5]

num_squared = []
for n in nums:
    squared = n**2
    num_squared.append(squared)

print(num_squared)  # Normal Way

[1, 4, 9, 16, 25]


In [ ]:
num_squared = [n**2 for n in nums] # list comprience 

print(num_squared) 

[1, 4, 9, 16, 25]


In [144]:
[i**2 for i in range(1,11)] # list compraience its faster == for loop 
#                               Use When : Login is simple, Need to transform of filter 

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [146]:
# Dictionay Comprehansion -> Create dictionaries used an expression 
#                            can replace for loops and certain lambda functions 
# dictionary = {key: expression for (key,value) in iterable}

cities_in_F = {'New York': 32, 'Boston':75, 'Los Angeles':100, 'Chicago': 50}

cities_in_C = {key: round((value-32)*(5/9)) for (key,value) in cities_in_F.items()}

print(cities_in_C)

{'New York': 0, 'Boston': 24, 'Los Angeles': 38, 'Chicago': 10}


In [147]:
weather = {'New York': 'snowing', 'Boston':'sunny','Los Angeles':'sunny', 'Chicago': 'cloudy'}

sunny_wether = {key:value for (key,value) in weather.items() if value == 'sunny'}

print(sunny_wether)

{'Boston': 'sunny', 'Los Angeles': 'sunny'}


In [150]:
weather = {'New York': 'snowing', 'Boston':'sunny','Los Angeles':'sunny', 'Chicago': 'cloudy'}

sunny_wether = {key:value for (key,value) in weather.items() if value == 'sunny'}

print(sunny_wether)

{'Boston': 'sunny', 'Los Angeles': 'sunny'}


In [151]:
cities = {'New York': 32, 'Boston':75, 'Los Angeles':100, 'Chicago': 50}

desc_cities = {key:('Warn' if value >= 40 else 'Cold') for (key,value) in cities.items()}

print(desc_cities)

{'New York': 'Cold', 'Boston': 'Warn', 'Los Angeles': 'Warn', 'Chicago': 'Warn'}


In [157]:
# If-elif-else statements -> Do some code only IF some condition is True 
#                            Else do somthing else

age = int(input('Enter your age: '))

if age >= 18:
    print('You are now signed up!')
elif age < 0:
    print('You are not eligible')
else:
    print('You must be 18+ to sign up')



You are now signed up!


In [163]:
# while loop = execute some code WHILE some conditio remains true 

food = input('Enter a food you like (q to quit) ')

while not food == 'q':
    print(f'You like {food}')
    food = food = input('Enter another food you like (q to quit) ')

print('bye')

    

You like pizza
You like pizza
bye


In [167]:
# for loop  = execute a block of code a fixed number of times.
#               you can iterate over a range, string, sequence,etc.

for counter in range(1,11,2):
    print(counter)

1
3
5
7
9


In [166]:
for counter in reversed(range(1,11)):
    print(counter)

print("Happy New Year!")

10
9
8
7
6
5
4
3
2
1
Happy New Year!


In [172]:
# Nested loop = A loop within another loop (outer, inner)
#               outer loop:
#                   inner loop:

for x in range(3):
    for j in range(1,10):
        print(j, end='')
    print()

123456789
123456789
123456789


In [174]:
# function = A block of reusable code 
#             place () after the function name to invoke it 

def display_income(username,amount, due_date):
    print(f'Hello {username}')
    print(f'Your bill of ₹{amount:.2f} is due:{due_date}')


display_income('Naidu', 20000 ,'01/01')

Hello Naidu
Your bill of ₹20000.00 is due:01/01


In [178]:
# return = statemnet used to end a function 
#           and send a result back to the caller 

def add(x,y):
    z = x + y
    return z

def divide(x,y):
    z = x / y
    return z

print(add(3,5))
print(divide(10,2))

8
5.0


In [ ]:
# Lambda function = A small anonymous function for a one time use(throw away function)
#                   They take any number of arguments, but have only 1 expression
#                   Helps keep the namespace clean and is usefull with higher order functions 
#                   'sort()', 'map()', 'filter()', 'reduce()'
#                   lambda parameters: expression

double = lambda x:x * 2
add = lambda x,y:x + y

print(double(2))
print(add(2,2))


4
4


In [183]:
max_value = lambda x,y :x if x > y else y

print(max_value(6,5))

min_value = lambda x,y : x if x < y else y

print(min_value(8,5))

6
5


In [185]:
# *args = allows you to pass multiple non-key arguments 
# **kwargs = allows you to pass multiple keywords-agruments 
#               * unpacking operator 
#               1.positional  2.default 3.keyword 4.ARBITRATY

def add(x,y):
    return x + y

print(add(1,2))

3


In [190]:
def add_number(*args):
    total = 0
    for num in args:
        total += num
    return total

print(add_number(1,2,3))
print(add_number(5,10,15,20))

6
50


In [191]:
def student_info(**kwargs):
    for key,value in kwargs.items():
        print(key,':', value)

student_info(name='Naidu', age=30, course='python')

name : Naidu
age : 30
course : python


In [192]:
# *args + **kwargs

def demo(*args, **kwargs):
    print('Args:', args)
    print('Kwargs:', kwargs)


demo(1,2,3, name='Naidu',city='Mumbai')

Args: (1, 2, 3)
Kwargs: {'name': 'Naidu', 'city': 'Mumbai'}


In [196]:
# Local Scope 
# jo Variable function ke andar define hot hai 
# sirf usi function ke andar use ho sakta hai 

def my_func():
    x = 10 # local variable 
    print(x)

my_func()
# print(x) -> error  x srif my_func() ke andar exist karta ha 
# Function ke bahar x ko access nai kar sakte 
# Local = Function ke ander 

10


In [199]:
# Global Scope 
# jo variable function ke bahar define hota hai 
# poore program me acesss ho sakta hai 

y = 20 

def show():
    print(y)

show()
print(y)

# y function ke andar bhi use ho raha ha 
# aur function ke bhar bhi

20
20


In [201]:
# Global keyword ka use 
# Agar app function ke andar global variable ko change karna chahte ho: 

z = 5

def update():
    global z
    z = 10 

print(update())
print(z)

None
10


In [ ]:
# Nonlocal Scope 
# jab nested function (function ke andar function) ho 
# Aur inner function ko outer function ke variable ko change karna ho 

def outer():
    a = 50 

    def inner():
        nonlocal a
        a = 100

    inner()
    print(a)

outer()

# a outer function ka variable hai 
# inner function normally change nahi kar sakta 
# nonlocal bolta hai : 'Bhai outer function wala variable use karo'

100


In [ ]:
# Classes and Object 
# Class ek blueprint/design/plan hota hai 
# object class se bani hui real cheez , jo actually exist karta hai 

class Student:

    def __init__(self,name,age):
        self.name = name
        self.age = age

    def introduce(self):
        print('Mera naam', self.name, 'hai aur meri age',self.age, 'hai')


# Object create karna 
s1 = Student('Naidu', 20 )
s2 = Student('jerry', 30)

s1.introduce()
s2.introduce()


# Student -> Class
# s1 aut s2 -> Objects
# name,age -> properties (Attributes)
# introduce() -> Method(Funcion)

Mera naam Naidu hai aur meri age 20 hai
Mera naam jerry hai aur meri age 30 hai


In [205]:
# Inheritance 
# Socho:
# Parent -> Hieght, Eye color
# Child -> Same height, same eye + apna extra qualities 

class Animal:
    def speak(self):
        print('Animal bol raha hai')

class Dog(Animal):
    def bark(self):
        print('Dog bhook raha hai')


# Object create 
d = Dog()

d.bark() # Child class method 
d.speak() # Parent class method

Dog bhook raha hai
Animal bol raha hai


In [207]:
# Polymorphism 
# same function/ method, lekin different behavior.(ek hi chizz,alag-alag situation mein alag kaam karta hai)

# Python mein polymorphism mainly 2 ways se hota hai 
# 1.Method Overriding (inheritance ka saath)
# parent aur child class main same method name, lekin differnet implementation

class Animal:
    def sound(self):
        print('Animal sound')

class Dog(Animal):
    def sound(self):
        print('Dog bhonkta hai')

class Cat(Animal):
    def sound(self):
        print('Cat meow karti hai')


# object create
a = Animal()
d = Dog()
c = Cat()


a.sound()
d.sound()
c.sound()

# sound() method same hai 
# Behavior different hai -> this is Polymorphism 

Animal sound
Dog bhonkta hai
Cat meow karti hai


In [209]:
# 2.Method Overloading 
# python mein traditional overloading nai hota, lekin default arguments se achive kar sakte hain.as_integer_ratio

class Math:
    def add(self,a,b=0,c=0):
        return a+b+c
    
m = Math()

print(m.add(2))
print(m.add(2,3))
print(m.add(2,3,4))

# In Short Polymorphism ek Opp concept hai jisme same method ya function different forms mein behvae karta hai 

2
5
9


In [210]:
# Encapsulation 
# Data ka hide karna + controlled access dena = Encapsulation 
# Python mein encapsulation acess modifiers ke through acheve hot hai:
# 1. Public Member (Directly accesible)

class Student:
    def __init__(self,name,):
        self.name = name  # public 


s = Student('Naidu')
print(s.name)
        


Naidu


In [212]:
# 2. Protected Members(_)
# Indirectly access 
# Child class ke liya safe

class Student:
    def __init__(self):
        self._college = 'ABC College'

s = Student()
print(s._college) # allowed, but not recommended 

ABC College


In [215]:
# 3. Private Members(_)
# Direct access allowed nahi 
# Strong data hiding 

class Student:
    def __init__(self):
        self.__fees = 5000

    def show_fees(self):
        print(self.__fees)


s = Student()

s.show_fees()
# s.__fees -> Error 

5000


In [217]:
## Gette aur Setter Methods 

# Private data ko safely access/update karne ke liya use hota hain.as_integer_ratio

class Student:
    def __init__(self):
        self.__marks = 0

    def set_marks(self,m):
        if m >= 0:
            self.__marks = m 

    def get_marks(self):
        return self.__marks
    

s = Student()

s.set_marks(85)
print(s.get_marks())

# Encapsulation ek Opp concept hai jisme data aur methods ko ek unit mein bind kiya jata hai aur data ko direct access se hid kiya jata hai.

85


In [218]:
# Try-Except Blocks (Error handling ke liya use hota hai)

# try -> Yahan wo code likhte hain jisme error aa sakta hai 
# except -> agar error aaye, to yeh block execute hota hai 

try:
    a = 10 
    b = 0
    print(a/b)
except:
    print('Error aaya! Division by 0 allowed nahi hai.')

Error aaya! Division by 0 allowed nahi hai.


In [222]:
# Specific Error Handle Karna (Best Practice)

try:
    x = int(input('Number daalo: '))
    print(10 / x)
except ZeroDivisionError:
    print('Zero se divide nai kar sakte!')
except ValueError:
    print('Srif number daalo!')

# Explanation:
# Agar user 0 daale -> ZeroDivisionError
# Afar user tst daale -> ValueError
# har error ka alag message 

Zero se divide nai kar sakte!


In [224]:
# else Block 
# else tab chalta hai jab error nahi aata 

try: 
    num = int(input('Number: '))
    print(100/ num)
except ZeroDivisionError:
    print('Zero allowed nahi')
else:
    print('Calculation successfull!')

10.0
Calculation successfull!


In [225]:
# Finally Block 
# Finally hamesha chalega, error aaya ya na aaye 

try:
    f = open('data.txt')
    print(f.read())
except:
    print('file nai mila')
finally:
    print('Program end ho raha hai')

file nai mila
Program end ho raha hai


In [ ]:
# Raising Exceptions 
# Why Raise Exception?
# - input galat hota hai 
# - business rule break hota hai 
# - Aage ka code runnai hona chahiya 

a = -5 

if a < 0:
    raise ValueError('Age negative nai ho sakti')

# Age negative logically galat hai 
# isliya hum ValueError khud se raise kar raha hain 
# program wahi ruk jaaayega 

ValueError: Age negative nai ho sakti

In [230]:
# Raise with Try-Except 
try:
    num = int(input('Number daalo: '))
    if num == 0:
        raise ZeroDivisionError('Zero allowed nahi hai')
    print(10/ num)
except ZeroDivisionError as e:
    print('Error:',e)

Error: Zero allowed nahi hai


In [ ]:
# Custom Login Example 

balance = 500

withdrow = 1000

if withdrow > balance:
    raise Exception('Insufficient balance!') # bank system me yeh common use hota hai

Exception: Insufficient balance!

In [ ]:
# Custom Exception Class()
class InvalidAgeError(Exception):
    pass 

age = 15

if age < 18:
    raise InvalidAgeError('Age 18 se kam hai')

# Apna khud se error banaya 
# code jyada readable & professional baba jata hai 

InvalidAgeError: Age 18 se kam hai

In [243]:
# Reading & Writing Text Files 
# File Open Karna (Python me file open karne ke liya open() function use hota hai.)

file = open('data.txt', 'r')

# File Medos:
# 'r' -> Read(file padhna)
# 'w' -> Write(file me likhna, purana data delete ho jata hai)
# 'a' -> Append (file ke end me likhna)
# 'r+' -> read + write

In [242]:
# Puri File Ek Saath Read Karna 

file = open('data.txt', 'r')
content = file.read()
print(content)


Hello 
Naidu
Jerry and danfldfnd
fdanfldfodf dkf dofdofdffk dkfo
asdfdofnodkfnpdfmdl dfods fd


In [ ]:
file = open('data.txt','r') # Line by Line Read karna 
for line in file:
    print(line)
file.close()

Hello 

Naidu

Jerry and danfldfnd

fdanfldfodf dkf dofdofdffk dkfo

asdfdofnodkfnpdfmdl dfods fd


In [245]:
# readline() Method  (ek baar me sirf ek line read karta hai.)

file = open('data.txt','r')
line = file.readline() 
print(line)
file.close()

Hello 



In [250]:
# Writing Test File 
file = open('data.txt','w')
file.write('Hello Python!\n')
file.write('File handling is easy.')
file.close()

# Warning : 'w' mode purani file ka dta erese kar deta hai.

In [251]:
# Append Method 
file = open('data.txt', 'a')
file.write('\nNew line added')
file.close()  

# existing content safe rehta hai, new data end me add hota hai


In [252]:
# Best Practice with Statement 

with open('data.txt', 'r') as file:
    content = file.read()
    print(content)

Hello Python!
File handling is easy.
New line added


In [254]:
import csv # csv module import karna 

In [ ]:
with open('CardioGoodFitness.csv', 'r') as f:
    reader = csv.reader(f)
    for row in reader:
        print(row)

# Output har row ko list ke form me dega

['Product', 'Age', 'Gender', 'Education', 'MaritalStatus', 'Usage', 'Fitness', 'Income', 'Miles']
['TM195', '18', 'Male', '14', 'Single', '3', '4', '29562', '112']
['TM195', '19', 'Male', '15', 'Single', '2', '3', '31836', '75']
['TM195', '19', 'Female', '14', 'Partnered', '4', '3', '30699', '66']
['TM195', '19', 'Male', '12', 'Single', '3', '3', '32973', '85']
['TM195', '20', 'Male', '13', 'Partnered', '4', '2', '35247', '47']
['TM195', '20', 'Female', '14', 'Partnered', '3', '3', '32973', '66']
['TM195', '21', 'Female', '14', 'Partnered', '3', '3', '35247', '75']
['TM195', '21', 'Male', '13', 'Single', '3', '3', '32973', '85']
['TM195', '21', 'Male', '15', 'Single', '5', '4', '35247', '141']
['TM195', '21', 'Female', '15', 'Partnered', '2', '3', '37521', '85']
['TM195', '22', 'Male', '14', 'Single', '3', '3', '36384', '85']
['TM195', '22', 'Female', '14', 'Partnered', '3', '2', '35247', '66']
['TM195', '22', 'Female', '16', 'Single', '4', '3', '36384', '75']
['TM195', '22', 'Female',

In [257]:
# Header ke saath Read karna 
with open('CardioGoodFitness.csv','r')as f:
    reader = csv.DictReader(f)
    for row in reader:
        print(row)

# Output Dictionary ke form me hot hai

{'Product': 'TM195', 'Age': '18', 'Gender': 'Male', 'Education': '14', 'MaritalStatus': 'Single', 'Usage': '3', 'Fitness': '4', 'Income': '29562', 'Miles': '112'}
{'Product': 'TM195', 'Age': '19', 'Gender': 'Male', 'Education': '15', 'MaritalStatus': 'Single', 'Usage': '2', 'Fitness': '3', 'Income': '31836', 'Miles': '75'}
{'Product': 'TM195', 'Age': '19', 'Gender': 'Female', 'Education': '14', 'MaritalStatus': 'Partnered', 'Usage': '4', 'Fitness': '3', 'Income': '30699', 'Miles': '66'}
{'Product': 'TM195', 'Age': '19', 'Gender': 'Male', 'Education': '12', 'MaritalStatus': 'Single', 'Usage': '3', 'Fitness': '3', 'Income': '32973', 'Miles': '85'}
{'Product': 'TM195', 'Age': '20', 'Gender': 'Male', 'Education': '13', 'MaritalStatus': 'Partnered', 'Usage': '4', 'Fitness': '2', 'Income': '35247', 'Miles': '47'}
{'Product': 'TM195', 'Age': '20', 'Gender': 'Female', 'Education': '14', 'MaritalStatus': 'Partnered', 'Usage': '3', 'Fitness': '3', 'Income': '32973', 'Miles': '66'}
{'Product': 'T

In [258]:
# Json File read Karna 

import json 

with open('data.json', 'r') as f :
    data = json.load(f)

print(data)

{'name': 'Rahul', 'age': 21, 'city': 'Delhi'}


In [259]:
print(data['name'])

Rahul


### NumPy 

In [261]:
# Numpy Array 
# isme same type ka data store hota hai (int,flost,etc)
# ye C language ke level ki speed deta hai 

import numpy as np 

arr = np.array([1,2,3,4])

print(arr)

[1 2 3 4]


In [262]:
lst = [1,2,3,4]
print(lst * 2)

arr = np.array([1,2,3,4])
print(arr * 2)

[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


In [ ]:
# Numpy Array banane ke tareeke 
np.array([10,20,30,40]) 

array([10, 20, 30, 40])

In [265]:
np.zeros(3)

array([0., 0., 0.])

In [266]:
np.ones(4)

array([1., 1., 1., 1.])

In [267]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [272]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [275]:
# 1D Array 
a = np.array([1,2,3,4])

print(a)

[1 2 3 4]


In [ ]:
# 2D Array
b = np.array([[1,2],[3,4]])

print(b)

[[1 2]
 [3 4]]


In [279]:
# 3D Array
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(c)



[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [281]:
arr1 = np.array([[1, 2], [3, 4]])


In [286]:
# Array Atributions (Bahut important)

print(arr1.ndim) # Dimension

print(arr1.shape) # shape 

print(arr1.size) # Total Element

print(arr1.dtype) # Data Type

2
(2, 2)
4
int64


In [290]:
# Indexing & Slicing 

arr3 = np.array([10,20,30,40,50])

print(arr3[0])
print(arr3[-1])
print(arr3[1:3])

10
50
[20 30]


In [294]:
# 2D

mat = np.array([[1,2,3],[4,5,6]])

mat[0, 1]

np.int64(2)

In [297]:
# Mathematical Operations 
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [299]:
arr = [1,2,3,4,5,6]

In [301]:
# usefull Numpy Functions 

np.sum(arr)

np.int64(21)

In [302]:
np.mean(arr)

np.float64(3.5)

In [304]:
np.max(arr)

np.int64(6)

In [305]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [307]:
# Comparison Operations (boolearn Result)

arr = np.array([10,20,30])

arr > 15

array([False,  True,  True])

In [308]:
arr == 20

array([False,  True, False])

In [311]:
# Logical Operations 
a = np.array([True, False, True])
b = np.array([False, False, True])

np.logical_and(a,b)
np.logical_or(a,b)
np.logical_not(a,b)

array([False,  True, False])

In [ ]:
# Axis Based Operations 

mat = np.array([[1, 2, 3],
                [4, 5, 6]])

np.sum(mat, axis=0) # colum-wise (axis = 0)

array([5, 7, 9])

In [316]:
np.sum(mat, axis=1) # row- wise (axis = 1)

array([ 6, 15])

In [ ]:
# matrix Operations (2D Array) 
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

a * b  # Element-wise Multiplication


array([[ 5, 12],
       [21, 32]])

In [ ]:
np.dot(a,b) # matris Multiplication 

array([[19, 22],
       [43, 50]])

In [319]:
a @ b

array([[19, 22],
       [43, 50]])

In [320]:
# Sorting Operations

arr = np.array([40, 10, 30, 20])

np.sort(arr)


array([10, 20, 30, 40])

In [321]:
# Unique & Count 

arr = np.array([1, 2, 2, 3, 3, 3])

np.unique(arr)


array([1, 2, 3])

In [322]:
np.unique(arr, return_counts=True)

(array([1, 2, 3]), array([1, 2, 3]))

In [324]:
# Where Condition 

arr = np.array([10, 20, 30, 40])

np.where(arr > 25)
np.where(arr > 25, 'High', 'Low')

array(['Low', 'Low', 'High', 'High'], dtype='<U4')

In [327]:
# Reshape, Flatten $ Transpose 

arr = np.array([1,2,3,4,5,6])

arr.reshape(2,3)

arr.flatten()

array([1, 2, 3, 4, 5, 6])

In [328]:
mat.T

array([[1, 4],
       [2, 5],
       [3, 6]])